-- Check user name is system
SHOW USER;

/* CREATE USER MS_AUTHORITY */
CREATE USER MS_AUTHORITY IDENTIFED BY authority1;

GRANT CREATE SESSION TO MS_AUTHORITY;
GRANT CREATE TABLE TO MS_AUTHORITY;
GRANT CREATE SEQUENCE TO MS_AUTHORITY;
GRATN CREATE VIEW TO MS_AUTHORITY;
GRANT CREATE SESSION, RESOURCE TO MS_AUTHORITY;

ALTER USER MS_AUTHORITY DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

@createTable_authority.sql 

/* CREATE USER MS_ADMIN */
CREATE USER MS_ADMIN IDENTIFED BY admin1;

GRANT CREATE SESSION TO MS_ADMIN;
GRANT CREATE TABLE TO MS_ADMIN;
GRANT CREATE SEQUNCE TO MS_ADMIN;
GRANT CREATE VIEW TO MS_ADMIN;
GRANT CREATE SESSION, RESOURCE TO MS_ADMIN;

ALTER USER MS_ADMIN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT SELECT ON AUTHORITY TO MS_ADMIN;
GRANT INSERT ON AUTHORITY TO MS_ADMIN;