-- 7. 회의실 테이블 생성
CREATE TABLE MEETINGROOM (
	MT_NO VARCHAR2(7),				-- 회의실번호 PK
	BR_NO VARCHAR2(5),				-- 지사번호 FK
	EMP_NO VARCHAR2(14),			-- 예약자번호 FK
	MT_NM VARCHAR2(20),				-- 회의실명
	MT_START DATE,					-- 예약시작일자
	MT_END DATE,					-- 예약종료일자
	CONSTRAINT MT_PK PRIMARY KEY(MT_NO),
	CONSTRAINT MT_FK_BR FOREIGN KEY(BR_NO) REFERENCES BRANCH(BR_NO),
	CONSTRAINT MT_FK_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

-- 14. 카테고리 테이블 생성
CREATE TABLE NOTICE_TYPE (
	NT_NO NUMBER(2),				-- 카테고리번호 PK
	NT_NM VARCHAR2(8),				-- 카테고리명
	CONSTRAINT NT_PK PRIMARY KEY(NT_NO)
);

-- 13. 공지사항 테이블 생성
CREATE TABLE NOTICE (
	NOTI_SEQ NUMBER,				-- 공지사항번호 PK
	EMP_NO VARCHAR2(14),			-- 사원번호
	NT_NO NUMBER(2),				-- 카테고리번호 FK
	NOTI_TITLE VARCHAR2(100),		-- 제목
	NOTI_CONTENT VARCHAR2(4000),	-- 내용
	NOTI_CNT NUMBER(5),				-- 조회수
	NOTI_FILE VARCHAR2(200),		-- 파일
	NOTI_IN DATE,					-- 입력일자
	NOTI_UP DATE,					-- 수정일자
	NOTI_DE DATE,					-- 삭제일자
	CONSTRAINT NOTI_PK PRIMARY KEY(NOTI_SEQ),
	CONSTRAINT NOTI_FK_NT FOREIGN KEY(NT_NO) REFERENCES NOTICE_TYPE(NT_NO)
);

-- 공지사항 시퀀스 생성
CREATE SEQUENCE NOTI_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 100000000;
